### ISSUE TITLE
Layer 4 load balancer - no route to host

### ISSUE THREAD

**Issue by germal** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#10]
Hi Marc and Scott

Thank for the great book !
I am stuck at chapter 6, trying to create Layer 4 load balancer.
**curl 172.17.200.100:8080 -> No route to host**

I used the following command with the related yaml file , replacing something that maybe is related to my version.

kubectl create deployment nginx-web --image bitnami/nginx **( replaced run with create deployment )**

kubectl apply -f nginx-lb.yaml **<-- replaced run selector with app**
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: nginx-web   
  type: LoadBalancer

**My logs** 

**kubectl get  services -n default**
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)          AGE
kubernetes   ClusterIP      10.96.0.1       <none>           443/TCP          3h40m
nginx-lb     LoadBalancer   10.99.118.146   172.17.200.100   8080:30968/TCP   67m

**kubectl describe service nginx-lb**
Name:                     nginx-lb
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=nginx-web
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.107.8.242
IPs:                      <none>
LoadBalancer Ingress:     172.17.200.100
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30869/TCP
Endpoints:                192.168.189.139:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason        Age   From                Message
  ----    ------        ----  ----                -------
  Normal  IPAllocated   6s    metallb-controller  Assigned IP "172.17.200.100"
  Normal  nodeAssigned  6s    metallb-speaker     announcing from node "cluster01-worker"

 **kubectl describe  pod -n default**
Name:         nginx-web-5c9b7f757-zdf2b
Namespace:    default
Priority:     0
Node:         cluster01-worker/172.18.0.2
Start Time:   Tue, 04 May 2021 16:45:02 +0200
Labels:       app=nginx-web
              pod-template-hash=5c9b7f757
Annotations:  cni.projectcalico.org/podIP: 192.168.189.139/32
              cni.projectcalico.org/podIPs: 192.168.189.139/32
Status:       Running
IP:           192.168.189.139
IPs:
  IP:           192.168.189.139

Could you please help to debug ? @mlbiam @ssurovich 
Thanks a lot 
Regards

**Comment by ssurovich** [comment]
Hi @germal  -- Thanks for the book compliment, glad you are enjoying the book so far.

The first part I need to verify is what network the Docker bridge is on -  if you check using docker network inspect bridge, does it reply with 172.17.0.0/16?

**Comment by germal** [comment]
Hello @ssurovich ,

Thank you for your reply .
Yes the docker network is that :

           "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]

EDIT :would be possible to let a Kind container access to a web repo on Github or should I create another  container inside Kind with the clone of the Github repo ?
Thanks

**Comment by ssurovich** [comment]
Thanks for the verification on the Subnet (I assumed it was set to 172.17.0.0 but just wanted to make sure).

Next question - Are you running on Ubuntu, RHEL, etc...?

I'll reproduce the test in my home lab a little later today just to make sure nothing has changed that may have impacted the hands-on exercise.

On your question - I would recommend that the Repo is cloned to the Docker Host itself, not a container on the Host.  However, a Kind container shouldnt have any issues accessing the Web to clone the repo.

**Comment by germal** [comment]
Hello Scott
I use Ubuntu 18.04 as Host.
Thanks for your explanation,I have to check why it doesn't access to github.

**Comment by ssurovich** [comment]
Hi @germal  -  Sorry for my delayed reply, I thought I replied last week and just realized I didnt send the comment.

You found an update from the version of KinD the chapter was based on versus the behavior of newer versions.  In KinD 0.7 the clusters all used the default Docker bridge network, in 0.8, KinD started to create a new bridge for clusters called kind.  So - I believe your issue is due to the docker network - 172.17.0.0 is the default Docker bridge and kind is using the kind Docker network, which is likely 172.18.0.0 on your host.   

On page 169/170 it says to get the IP range from the docker network inspect bridge, but that should docker  network inspect kind.

If your kind bridge does match the 172.18.0.0/16 range, you can edit the metallb-config.yaml file, so it will look like the below:

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.18.200.100-172.18.200.125

Please let me know if this does resolve your issue.  Sorry for the delay in this reply again.

**Comment by ssurovich** [comment]
Since I have tested this a few times now, I believe it will resolve your issue - If it doesnt, please re-open the issue and I will help.
