### ISSUE TITLE
Chapter's 14 Create New Namespace throws java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by bmutziu** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#11]
Hello,

Again, thank you for this true piece of knowledge that your book is !

Everything went smoothly throughout all the chapters until the final one, when I've reached the error mentioned in the title.

Please let me provide some insights on the actual matter, when **https://k8sou.apps.xx-xx-xx-xxx.nip.io/newproject/index.html** is called:

- openunison-orchestra starts to complain about _"data too long for column"_ for **workflowObj** and **MSG** (tables being approvals and ACTIVEMQ_MSGS)
To overcome this I had to alter the columns from _text to mediumtext_ and and _mediumblob to longblob_ respectively.

- from this point on, the whole system needed to be bumped up in order to have things going:
  -  mariadb: has args _--max_allowed_packet=1073741824_
  - amq-orchestra: activemq.xml has _wireFormat.maxFrameSize=1048576000_ and heap size is _-Xms13G -Xmx13G_
  - openunison-orchestra: heap size  _-XX:InitialRAMPercentage=73.0 -XX:MinRAMPercentage=73.0 -XX:MaxRAMPercentage=73.0 -XX:MaxPermSize=128M -XX:+UseCompressedOops_ 

### GKE Cluster Node Pool:
                                                              Nodes 
 devops-selfservice|Ok|1.20.6-gke.1000 | 2 | **n2-standard-8** | Ubuntu with Docker (ubuntu) | 2 - 3 nodes per zone

- after all these tweaks the ACTIVEMQ.DLQ queue tasks were failing on the openunison-orchestra pod with the above-mentioned message: **"java.lang.OutOfMemoryError: Requested array size exceeds VM limit"** though the respective mapping groups have been created in GitLab ...
   The workflow stops after the OOM is happening.

IMHO the whole saga with the columns altering changed the actual course of things.

@mlbiam please let me know if you need anything else as I have the GKE cluster up these days.
 
Thank you,

Bogdan

**Comment by bmutziu** [comment]
Relevant lines from openunison-orchestra deployment:

java.lang.OutOfMemoryError: Requested array size exceeds VM limit
Dumping heap to /usr/local/openunison/config/rchstr.hprof ...
Heap dump file created [12173869364 bytes in 27.975 secs]
[2021-05-25 10:14:58,979][Thread-23] INFO  K8sLoadTrusts - watching https://10.3.240.1:443/apis/openuniso
n.tremolo.io/v1/namespaces/openunison/trusts?watch=true&timeoutSeconds=10
[2021-05-25 10:14:58,979][Thread-12] INFO  LoadUrlsFromK8s - watching https://10.3.240.1:443/apis/openuni
son.tremolo.io/v1/namespaces/openunison/portalurls?watch=true&timeoutSeconds=10
[2021-05-25 10:14:58,978][ActiveMQ Session Task-7] ERROR ActiveMQMessageConsumer - ID:openunison-orchestr
a-646d6b9dc-5ktn2-32815-1621937410142-1:2:4:1 Exception while processing message: ID:openunison-orchestra
-646d6b9dc-5ktn2-32815-1621937410142-1:1:5:1:6
java.lang.RuntimeException: Could not execute task
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.lang.StringCoding.encode(StringCoding.java:350)
        at java.lang.String.getBytes(String.java:941)
        at com.cedarsoftware.util.io.JsonReader.<init>(JsonReader.java:579)
        at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:424)
        at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:399)
        at com.tremolosecurity.provisioning.core.TaskConsumer.onMessage(TaskConsumer.java:66)
        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404)
        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131)
        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202)
        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        at com.tremolosecurity.provisioning.core.TaskConsumer.onMessage(TaskConsumer.java:108) ~[unison-server-core-1.0.20.jar:?]
        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404) [activemq-client-5.15.12.jar:5.15.12]
        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [activemq-client-5.15.12.jar:5.15.12]
        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [activemq-client-5.15.12.jar:5.15.12]
        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.15.12.jar:5.15.12]
        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.15.12.jar:5.15.12]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.lang.StringCoding.encode(StringCoding.java:350) ~[?:1.8.0_265]
        at java.lang.String.getBytes(String.java:941) ~[?:1.8.0_265]
        at com.cedarsoftware.util.io.JsonReader.<init>(JsonReader.java:579) ~[json-io-4.12.0.jar:?]
        at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:424) ~[json-io-4.12.0.jar:?]
        at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:399) ~[json-io-4.12.0.jar:?]
        at com.tremolosecurity.provisioning.core.TaskConsumer.onMessage(TaskConsumer.java:66) ~[unison-server-core-1.0.20.jar:?]

Leak Suspects:

Problem Suspect 1

![Leak Suspect 1](https://user-images.githubusercontent.com/13050987/119615982-bcb61f00-be08-11eb-8127-9a25a595d419.png)
![Leak Suspect 1 Bis](https://user-images.githubusercontent.com/13050987/119615994-c2136980-be08-11eb-9fc4-45fd9cd1d73a.png)

Problem Suspect 2

![Leak Suspect 2](https://user-images.githubusercontent.com/13050987/119616270-16b6e480-be09-11eb-8b3d-9571908aa188.png)
![Leak Suspect 2 Bis](https://user-images.githubusercontent.com/13050987/119616282-1880a800-be09-11eb-9c61-961b675aaf55.png)
![Leak Suspect 2 ReBis](https://user-images.githubusercontent.com/13050987/119616290-1a4a6b80-be09-11eb-83bd-4c5f103c0f49.png)

@mlbiam Has anyone seen a happy ending to Chapter 14 ?

**Comment by mlbiam** [comment]
i've gotten it running in KinD and OCP a few times.  I have had to alter the workflow table before but it seems what's happening here is something is getting recursively stored.  These workflows just aren't that big.  openunison usually doesn't need more then 300-400 MB of memory per pod.  are there any workflows with data in the approvals table where worklfowObj is now null?  Can you tell me how big those objects are?

**Comment by bmutziu** [comment]
Before approving the request:

MariaDB [unison]> select id, approved, label, reason, approver, workflow from approvals where workflowObj
 IS NOT NULL;
+----+----------+----------------------------------------+--------+----------+----------+
| id | approved | label                                  | reason | approver | workflow |
+----+----------+----------------------------------------+--------+----------+----------+
| 37 |     NULL | Create New Application - dev-user-ns-h | NULL   |     NULL |      121 |
+----+----------+----------------------------------------+--------+----------+----------+

MariaDB [unison]> select * from workflows where id='121';
+-----+------------+------------------------------------------------------------------------------+-----------------+----------------+---------------+---------------------+-------------+--------+
| id  | completeTS | description                                                                  | label           | name           | requestReason | startTS             | requesterid | userid |
+-----+------------+------------------------------------------------------------------------------+-----------------+----------------+---------------+---------------------+-------------+--------+
| 121 | NULL       | Creates a new kubernetes namespace and associated groups to manage approvals | New Application | NewApplication | h             | 2021-05-26 23:25:20 |           1 |      1 |
+-----+------------+------------------------------------------------------------------------------+-----------------+----------------+---------------+---------------------+-------------+--------+


❯ l -Sh approvals.sql
-rw-rw-r-- 1 bmutziu bmutziu **157K** mai 27 02:26 **approvals.sql**

+---------------+--------------------------+---------+--------------+
| database_name | table_name               | used_mb | allocated_mb |
+---------------+--------------------------+---------+--------------+
**| unison        | approvals                |    0.36 |         0.36 |**
| unison        | QRTZ_TRIGGERS            |    0.20 |         0.20 |
| unison        | auditLogs                |    0.16 |         0.16 |
| unison        | ACTIVEMQ_MSGS            |    0.11 |         0.11 |
| unison        | QRTZ_FIRED_TRIGGERS      |    0.11 |         0.11 |
| unison        | oidcSessionState         |    0.08 |         0.08 |
| unison        | workflows                |    0.05 |         0.05 |
| unison        | allowedApprovers         |    0.05 |         0.05 |
| unison        | QRTZ_JOB_DETAILS         |    0.05 |         0.05 |
| unison        | userGroups               |    0.05 |         0.05 |
| unison        | QRTZ_BLOB_TRIGGERS       |    0.03 |         0.03 |
| unison        | approverAttributes       |    0.03 |         0.03 |
| unison        | escalation               |    0.03 |         0.03 |
| unison        | workflowParameters       |    0.03 |         0.03 |
| unison        | userAttributes           |    0.03 |         0.03 |
| unison        | ACTIVEMQ_ACKS            |    0.03 |         0.03 |
| unison        | auditLogType             |    0.02 |         0.02 |
| unison        | localUsers               |    0.02 |         0.02 |
| unison        | QRTZ_SIMPLE_TRIGGERS     |    0.02 |         0.02 |
| unison        | QRTZ_CALENDARS           |    0.02 |         0.02 |
| unison        | QRTZ_SIMPROP_TRIGGERS    |    0.02 |         0.02 |
| unison        | localGroups              |    0.02 |         0.02 |
| unison        | QRTZ_PAUSED_TRIGGER_GRPS |    0.02 |         0.02 |
| unison        | users                    |    0.02 |         0.02 |
| unison        | targets                  |    0.02 |         0.02 |
| unison        | approvers                |    0.02 |         0.02 |
| unison        | ACTIVEMQ_LOCK            |    0.02 |         0.02 |
| unison        | QRTZ_CRON_TRIGGERS       |    0.02 |         0.02 |
| unison        | QRTZ_LOCKS               |    0.02 |         0.02 |
| unison        | QRTZ_SCHEDULER_STATE     |    0.02 |         0.02 |
+---------------+--------------------------+---------+--------------+


After completing the approval process and having the OOM:

MariaDB [unison]> select id, approved, label, reason, approver, workflow from approvals where workflowObj IS NOT NULL;
Empty set (0.000 sec)

Note: for _workflowObj equalling NULL_ we have the above-metioned record w/ _id 37 and workflow 121_ ...
+---------------+--------------------------+---------+--------------
| database_name | table_name               | used_mb | allocated_mb |
+---------------+--------------------------+---------+--------------+
**| unison        | ACTIVEMQ_MSGS            |  907.11 |      1193.11 |**
| unison        | QRTZ_TRIGGERS            |    0.20 |         0.20 |
| unison        | auditLogs                |    0.16 |         0.16 |
| unison        | QRTZ_FIRED_TRIGGERS      |    0.11 |         0.11 |
| unison        | oidcSessionState         |    0.08 |         0.08 |
| unison        | approvals                |    0.05 |         0.05 |
| unison        | userGroups               |    0.05 |         0.05 |
| unison        | workflows                |    0.05 |         0.05 |
| unison        | allowedApprovers         |    0.05 |         0.05 |
| unison        | QRTZ_JOB_DETAILS         |    0.05 |         0.05 |
| unison        | workflowParameters       |    0.03 |         0.03 |
| unison        | userAttributes           |    0.03 |         0.03 |
| unison        | ACTIVEMQ_ACKS            |    0.03 |         0.03 |
| unison        | QRTZ_BLOB_TRIGGERS       |    0.03 |         0.03 |
| unison        | approverAttributes       |    0.03 |         0.03 |
| unison        | escalation               |    0.03 |         0.03 |
| unison        | users                    |    0.02 |         0.02 |
| unison        | targets                  |    0.02 |         0.02 |
| unison        | approvers                |    0.02 |         0.02 |
| unison        | ACTIVEMQ_LOCK            |    0.02 |         0.02 |
| unison        | QRTZ_CRON_TRIGGERS       |    0.02 |         0.02 |
| unison        | QRTZ_LOCKS               |    0.02 |         0.02 |
| unison        | QRTZ_SCHEDULER_STATE     |    0.02 |         0.02 |
| unison        | auditLogType             |    0.02 |         0.02 |
| unison        | localUsers               |    0.02 |         0.02 |
| unison        | QRTZ_SIMPLE_TRIGGERS     |    0.02 |         0.02 |
| unison        | QRTZ_CALENDARS           |    0.02 |         0.02 |
| unison        | QRTZ_SIMPROP_TRIGGERS    |    0.02 |         0.02 |
| unison        | localGroups              |    0.02 |         0.02 |
| unison        | QRTZ_PAUSED_TRIGGER_GRPS |    0.02 |         0.02 |
+---------------+--------------------------+---------+--------------+

❯ l -Sh ACTIVEMQ_MSGS.sql
-rw-rw-r-- 1 bmutziu bmutziu **897M** mai 27 02:44 ACTIVEMQ_MSGS.sql

Also,

MariaDB [unison]> select ID, CONTAINER,  MSGID_PROD, MSGID_SEQ, EXPIRATION, PRIORITY, XID from ACTIVEMQ_MSGS;
+-----+----------------------+---------------------------------------------------------------------+-----------+------------+----------+------+
| ID  | CONTAINER            | MSGID_PROD                                                          | MSGID_SEQ | EXPIRATION | PRIORITY | XID  |
+-----+----------------------+---------------------------------------------------------------------+-----------+------------+----------+------+
| 196 | queue://ActiveMQ.DLQ | ID:openunison-orchestra-646d6b9dc-qczcc-46185-1622068837983-1:1:6:1 |         6 |          0 |        0 | NULL |
+-----+----------------------+---------------------------------------------------------------------+-----------+------------+----------+------+

**Comment by mlbiam** [comment]
@bmutziu i think we found the issue.  it had nothing to do with the book's setup but was a bug in handling non ascii characters in openunison's workflows.  (https://github.com/TremoloSecurity/OpenUnison/issues/561).  That said, we're in the process of writing a second edition and i'm updating this chapter.  If you're willing to help test it out I'll make sure you get a free copy of the new edition.
