### ISSUE TITLE
Trying to generate metadata for RP throws 404 Not Found

### ISSUE THREAD

**Issue by kushan22** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#13]
Hi, After deploying openunison pods, Kubernetes Dashboard and Ingress Controller I was trying to get the metadata information for the relying party and I am getting 404 not found.
![image](https://user-images.githubusercontent.com/14822234/128259888-0d86a121-b3f4-4645-9cab-d8da277e635d.png)

**Comment by mlbiam** [comment]
@kushan22 run `kubectl get ingress -n openunison`, what comes up?

**Comment by mlbiam** [comment]
I found the issue.  openunison's operator was updated to move from ingress v1beta --> v1, but the book was written to 1.18 before v1 was released.  We fixed the operator so it will work with both.  This should get you back on track:

First, delete your orchestra deployment:

```
helm delete orchestra -n openunison
```
Next, update your helm repo and update your operator
```
helm repo update
helm upgrade openunison tremolo/openunison -n openunison
kubectl delete pods -l app=openunison-operator -n openunison
```

Then delete the operator pod to pull the latest version

Finally re-install the `orchestra` chart

**Comment by kushan22** [comment]
Yes, that works thanks but I am not able to reach kubernetes dashboard.
Here is my operator logs
![image](https://user-images.githubusercontent.com/14822234/128403635-341b4c19-1138-47fb-b665-0fc9417335ca.png)


It looks like some authentication issue. 403 forbidden

**Comment by mlbiam** [comment]
your able to get to the openunison portal, but not the kubernetes dashboard?

**Comment by kushan22** [comment]
Yes thats correct

**Comment by mlbiam** [comment]
screenshot?

**Comment by kushan22** [comment]
Here is the screenshot:
![image](https://user-images.githubusercontent.com/14822234/128406188-5e6f6b54-10f3-46a5-91f7-b3de1254eb79.png)

**Comment by mlbiam** [comment]
what do the `openunison-orchestra` pod's logs say?

**Comment by kushan22** [comment]
![image](https://user-images.githubusercontent.com/14822234/128406827-0e844ab7-9dc7-4c5d-8e41-d7d7a411f7e8.png)
This is what I see in the orchestra logs

**Comment by mlbiam** [comment]
I think you missed deploying the dashboard.  `kubectl get ns` ?

**Comment by kushan22** [comment]
Here is my dashboard:
![image](https://user-images.githubusercontent.com/14822234/128408032-120afde8-80b2-4d5e-92bb-2b275adea187.png)

**Comment by mlbiam** [comment]
Sorry, I misread the logs.  It looks like your container can't connect to your cluster's worker nodes.  @ssurovich any thoughts as to why the openunison container can't connect to the Ingress on node IP 192.168.43.55?

**Comment by mlbiam** [comment]
(@kushan22  you can temporarily work around this by adding:

```
openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: saml
```

to your values.yaml.  I suspect the OIDC integration with your cluster will still fail because your API server won't be able to communicate with your Ingress.  But Impersonation will work)

**Comment by nithikpackt** [comment]
Thank you for the solution @mlbiam . I am closing the issue for now.
