### ISSUE TITLE
Granting Docker Permissions - Update

### ISSUE THREAD

**Issue by somayedubati** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#5]
I was working on the following section in the guide page#13. Please review below and update.

Below 2 commands exist in the book. Even after executing them I was getting permission denied error.
sudo groupadd docker
sudo usermod -aG docker $USER

Error Message:
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.

I had to run the following command to in order to allow non-root user for executing docker commands.
sudo chmod 777 /var/run/docker.sock

Below is the screen shot. 
![image](https://user-images.githubusercontent.com/57639540/100694113-5326ed80-335c-11eb-96c5-870482cbfbb7.png)

Thank You!

**Comment by mlbiam** [comment]
when you change the permissions you need to logout of your existing session (whether it's SSH or terminal) and log back in for the permissions to take effect.  Changing the permissions on `/var/run/docker.sock` just opens it for everyone and even though its for a development environment shouldn't be done.

**Comment by somayedubati** [comment]
Thank You! I will try without changing permissions in another SSH console..

**Comment by ssurovich** [comment]
Hi @somayedubati - Did you have issues after that, we just want to make sure that you are good so you can continue with the exercises.

**Comment by somayedubati** [comment]
Hi @ssurovich, Sorry for the delays to retesting without changing permissions. By opening a new SSH console worked fine without any permission denied issues.

Thanks a lot!

![image](https://user-images.githubusercontent.com/57639540/101289287-84bf0f00-37c9-11eb-96a1-d80c8d4796c0.png)

**Comment by ssurovich** [comment]
@somayedubati - Great to hear, thanks for the reply.  No worried at all on taking time to reply, we appreciate the confirmation and are here to help :)
