### ISSUE TITLE
Deleting Cluster Command Typo

### ISSUE THREAD

**Issue by somayedubati** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#6]
Please review below and update. A Hyphen missing in the options.
Page# 81
kind delete cluster -name <cluster name>

Update:
kind delete cluster --name <cluster name>

**Comment by ssurovich** [comment]
@somayedubati - Thanks, that must have been missed or removed during one of the editing stages.

As you have correctly stated, the command syntax should be **kind delete cluster --name <cluster name>**
