### ISSUE TITLE
Persistent Volume Claim test creation failing

### ISSUE THREAD

**Issue by somayedubati** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#7]
Following the section "Using KinD's storage provisioner" section and setting up the PVC with the provided example page# 94..
It's keep failing as mentioned in the Problem#2.  Please review the attached YAML and advise If I am making any mistake.

Problem#1: 
Description:
Getting the following error due to syntax issue with restartPolicy: "Never". 

ubuntu@DockerOne:~$ kubectl create -f pvccreate.yaml
persistentvolumeclaim/test-claim created
error: error parsing pvccreate.yaml: error converting YAML to JSON: yaml: line 17: did not find expected key

Problem#2:
Description:
Removed the double quotes from the restartPolicy mentioned in the Problem#1 and then try to create but getting an error below.

ubuntu@DockerOne:~$ kubectl create -f pvccreate.yaml
persistentvolumeclaim/test-claim created
error: error parsing pvccreate.yaml: error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context
ubuntu@DockerOne:~$

![image](https://user-images.githubusercontent.com/57639540/100697310-a81a3200-3363-11eb-8e42-a974203c2109.png)

Thanks a lot for your help!

[pvccreate.yaml.txt](https://github.com/PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide/files/5620262/pvccreate.yaml.txt)

**Comment by ssurovich** [comment]
Hi @somayedubati - Sorry for the delay in this, I will test it a little later today and reply with any issues/resolutions tonight.

**Comment by ssurovich** [comment]
Hi @somayedubati  - Its a minor syntax in your manifest, it can be a challenge to see the correct format in just the book.

Its the bottom portion of you manifest, the restartPolicy field needs to be indented two spaces, and the last section with the Volumes is two space two far indented.  The corrected manifest is below:

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pvc-claim
spec:
  containers:
  - name: test-pod
    image: busybox
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/test && exit 0 || exit 1"
    volumeMounts:
      - name: test-pvc
        mountPath: "/mnt"
  restartPolicy: Never
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-claim


If you execute this, it will succeed:

persistentvolumeclaim/test-claim created
pod/test-pvc-claim created

Any issues you can reopen the issue.

**Comment by somayedubati** [comment]
Thanks a lot for your time in reviewing the YAML file!  I am able to fix and created the PV, and PVC's successfully.

![image](https://user-images.githubusercontent.com/57639540/101290913-ffd8f300-37d2-11eb-8fbd-8852124d7a75.png)

Attached the file for any future references if anyone required,
[pvccreate.yaml.txt](https://github.com/PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide/files/5649455/pvccreate.yaml.txt)

**Comment by ssurovich** [comment]
@somayedubati - Excellent!  Thanks for the confirmation - and no problem at all, happy to help out with questions.  Hopefully you're enjoying the book and learning something new?  :)
