### ISSUE TITLE
There are no chapter4 folder in Github repository.

### ISSUE THREAD

**Issue by mstrello** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#8]
Hi there! 

I am following the e-book (directly from Packt site) and in Chapter 4 when you need to create a custom cluster (Chapter 4, Section "Creating a KinD cluster"), there is a reference to the repository file `"/chapter4/cluster01-kind .yaml"`. But there is no chapter4 folder in the Github repository (at least I didn't see one, sorry if I'm wrong).

**Comment by ssurovich** [comment]
Hi @mstrello - Sorry about that - originally, we had the KinD chapter as Chapter 5 but we shuffled the Bootcamp and KinD chapters around, so the KinD Chapter was Chapter 5 - We must have renamed the folder back to Chapter 5 in a Git update.  I have resolved that, renaming the chapter5 folder to chapter4.  Sorry for the confusion.

Thanks for pointing the error out.

**Comment by mstrello** [comment]
Hi @ssurovich , thanks you for the explanation.

**Comment by ssurovich** [comment]
:)  You're welcome - if you run into any other issues, just let us know.  Thanks again for pointing that chapter folder name change out.
